
-- Add new prompts to the daily_prompts table
INSERT INTO public.daily_prompts (prompt_text, order_position) VALUES
('Songs that played the week everything changed', 6),
('Songs that make you feel 17 again', 7),
('Songs that sound like your first love', 8),
('Songs that bring you back to your first apartment', 9),
('Songs that feel like your last summer before growing up', 10),
('Songs that remind you of being in the backseat', 11),
('Songs that got you through the breakup', 12),
('Songs that remind you of your middle school crush', 13),
('Songs that played in the car with your best friend', 14),
('Songs that helped you let go', 15),
('Songs that feel like your senior year soundtrack', 16),
('Songs that made you want to be better', 17),
('Songs that lived on your old laptop', 18),
('Songs that felt like a hug when you needed one', 19),
('Songs that helped you move on, even if it hurt', 20),
('Songs that you wish you could hear again for the first time', 21),
('Songs that sound like your hometown', 22),
('Songs that helped you forgive someone', 23),
('Songs that belong to someone you''re not in touch with anymore', 24),
('Songs that felt like falling in love', 25),
('Songs that reminded you of who you are', 26),
('Songs that made you want to scream', 27),
('Songs that made everything feel okay, even for a second', 28),
('Songs that feel like your first day of college', 29),
('Songs that played while packing up your childhood room', 30),
('Songs that remind you of someone you haven''t seen in years', 31),
('Songs that helped you figure it out', 32),
('Songs that sound like late-night texting', 33),
('Songs that made you want to run away', 34),
('Songs that played before something big happened', 35),
('Songs that remind you of your first party', 36),
('Songs that feel like making peace with the past', 37),
('Songs that brought you closer to someone', 38),
('Songs that sound like an old voicemail', 39),
('Songs that feel like being the last one awake', 40),
('Songs that remind you of the first time you felt understood', 41),
('Songs that felt like a turning point', 42),
('Songs that helped you through a fight', 43),
('Songs that made you text them', 44),
('Songs that lived on your best friend''s playlist', 45),
('Songs that feel like scrolling through old photos', 46),
('Songs that you shared with someone you loved', 47),
('Songs that make you feel safe', 48),
('Songs that remind you of the first place you ever lived', 49),
('Songs that brought you back to yourself', 50),
('Songs that feel like a secret', 51),
('Songs that helped you feel seen again', 52),
('Songs that you never skipped', 53);
