// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfogvhlkrwgywuzdgnxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmb2d2aGxrcndneXd1emRnbnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjI3MjIsImV4cCI6MjA2NTgzODcyMn0.N2mCh4uGLY6MxEcSqNeApkrfFrW2zH_JO6Tp4wF1ujk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);